---
- name: lookup credential type
  register: credential_type
  awx_lookup:
    api_url: "{{ awx_url }}"
    api_user: "{{ awx_username }}"
    api_password: "{{ awx_password }}"
    kind: "CredentialType"
    params: "{{ spec.credential_type }}"

- when: credential_type.resource.id is not defined
  fail:
    msg: "Unable to look up credential type."

- name: lookup organization
  when: spec.organization.name is defined
  register: organization
  awx_lookup:
    api_url: "{{ awx_url }}"
    api_user: "{{ awx_username }}"
    api_password: "{{ awx_password }}"
    kind: Organization
    params:
      name: "{{ spec.organization.name }}"

- when: organization.resource.id is not defined
  fail:
    msg: "Unable to look up organization."

- name: "create credential {{ spec.name }}"
  awx_credential:
    api_url: "{{ awx_url }}"
    api_user: "{{ awx_username }}"
    api_password: "{{ awx_password }}"
    credential_type: "{{ credential_type.resource .id }}"
    name: "{{ spec.name }}"
    organization_id: "{{ organization.resource.id }}"
    description: >-
      Kubernetes service account credentials for cluster {{ k8s_cluster_name }}.
    inputs: "{{ spec.inputs }}"
