---
- name: "lookup credential type"
  register: result
  awx_lookup:
    api_url: "{{ awx_url }}"
    api_user: "{{ awx_username }}"
    api_password: "{{ awx_password }}"
    kind: "CredentialType"
    params: "{{ item.credential_type }}"

- name: "lookup credential {{ item.name }}" 
  register: result
  awx_lookup:
    api_url: "{{ awx_url }}"
    api_user: "{{ awx_username }}"
    api_password: "{{ awx_password }}"
    kind: Credential
    params:
      credential_type: "{{ result.resource.id }}"
      organization_id: "{{ awx_organization_id }}"
      name: "{{ item.name }}"

- name: "set credentials for job template {{ awx_job_template_name }}"
  awx_job_template_ssh:
    api_url: "{{ awx_url }}"
    api_user: "{{ awx_username }}"
    api_password: "{{ awx_password }}"
    state: credential.state|default('present') == 'present'
    job_template_id: "{{ awx_job_template_id }}"
    credential_id: "{{ result.resource.id }}"
